
package net.webservicex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CCCheckerSoap", targetNamespace = "http://www.webservicex.net")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CCCheckerSoap {


    /**
     * Please enter card type as  VISA or MASTERCARD or DINERS or AMEX
     * 
     * @param cardType
     * @param cardNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ValidateCardNumber", action = "http://www.webservicex.net/ValidateCardNumber")
    @WebResult(name = "ValidateCardNumberResult", targetNamespace = "http://www.webservicex.net")
    @RequestWrapper(localName = "ValidateCardNumber", targetNamespace = "http://www.webservicex.net", className = "net.webservicex.ValidateCardNumber")
    @ResponseWrapper(localName = "ValidateCardNumberResponse", targetNamespace = "http://www.webservicex.net", className = "net.webservicex.ValidateCardNumberResponse")
    public String validateCardNumber(
        @WebParam(name = "cardType", targetNamespace = "http://www.webservicex.net")
        String cardType,
        @WebParam(name = "cardNumber", targetNamespace = "http://www.webservicex.net")
        String cardNumber);

}
